MEMORY
{
  FLASH : ORIGIN = 0xff000000, LENGTH = 320K
  RAM   : ORIGIN = 0xff100000, LENGTH = 448K
}
REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

